var Alexa = require('alexa-sdk');
 
exports.handler = function(event, context, callback){
    var alexa = Alexa.handler(event, context, callback);
};

var APP_ID = "amzn1.ask.skill.087c1849-609e-46ba-a5cd-8366fe17c8ba";

var SKILL_NAME = "Most Likely"
var GAME_LENGTH = data.lenth;
var GET_GAME_MESSAGE = "Welcome to the game of Most Likely. The rules are simple, I will ask a question, then everyone will point to the person they think is most likely to commit the act. That person has to drink."
var HELP_MESSAGE = "You can say pause to pause the game, or next for a new question."
var HELP_REPROMPT = "What can I help you with?"
var STOP_MESSAGE = "Thank you for playing. Please remember to drink responsibly!"

var data = [
	"Most likely to accidentally kill someone?",
	"Most likely to act in a porn flick?",
	"Most likely to adopt a dog?",
	"Most likely to always be happy?",
	"Most likely to always carry hand sanitizer?",
	"Most likely to appear on some reality show?",
	"Most likely to avoid using computers?",
	"Most likely to be a billionaire?",
	"Most likely to be a day dreamer?",
	"Most likely to be a drama queen?",
	"Most likely to be a gang member?",
	"Most likely to be a good hunter?",
	"Most likely to be a good photographer?",
	"Most likely to be a happy father?",
	"Most likely to be a millionaire?",
	"Most likely to be a serial killer?",
	"Most likely to be a spy?",
	"Most likely to be a stand-up comedian?",
	"Most likely to be a stingy dad?",
	"Most likely to be a supermodel?",
	"Most likely to be a witch?",
	"Most likely to be a wizard?",
	"Most likely to be a world traveler?",
	"Most likely to be an escaped prisoner?",
	"Most likely to be an only child?",
	"Most likely to be an undercover agent?",
	"Most likely to be broke again after winning the lottery?",
	"Most likely to be fake their own death?",
	"Most likely to be grumpy after a one night stand?",
	"Most likely to be in a choir?",
	"Most likely to be involved in a felony?",
	"Most likely to be late to an event?",
	"Most likely to be on a commercial?",
	"Most likely to be poor?",
	"Most likely to be president?",
	"Most likely to be rich?",
	"Most likely to be the best at math?",
	"Most likely to be the first one to die in a zombie apocalypse?",
	"Most likely to win the lottery?",
	"Most likely to become a bestselling author?",
	"Most likely to become a celebrity?",
	"Most likely to become a divorcee?",
	"Most likely to become a famous actor/actress?",
	"Most likely to become a father/mother before marriage?",
	"Most likely to become a gossip columnist?",
	"Most likely to become a high school teacher?",
	"Most likely to become a multi-millionaire?",
	"Most likely to become a pilot?",
	"Most likely to become a popular singer?",
	"Most likely to become a president of United States of America?",
	"Most likely to become a priest/nun?",
	"Most likely to become a serial killer?",
	"Most likely to become a sports star?",
	"Most likely to become a successful politician?",
	"Most likely to become a super villain?",
	"Most likely to become a terrorist?",
	"Most likely to become a world famous actor (or actress) one day?",
	"Most likely to become an alcoholic?",
	"Most likely to become an astronaut?",
	"Most likely to become bald headed?",
	"Most likely to become famous?",
	"Most likely to betray their friends?",
	"Most likely to binge watch a movie a day to an exam?",
	"Most likely to blow all their money on an impulse buy?",
	"Most likely to boycott the beauty industry?",
	"Most likely to break into a house?",
	"Most likely to break some world record?",
	"Most likely to break their phone screen?",
	"Most likely to bring a book to a party?",
	"Most likely to burn someone’s house down?",
	"Most likely to buy the most expensive pair of shoes?",
	"Most likely to buy the most expensive perfume?",
	"Most likely to camp in a jungle?",
	"Most likely to catch a grenade for a loved one?",
	"Most likely to catch a thief alone?",
	"Most likely to catch a cold within next 24 hours?",
	"Most likely to cause world war?",
	"Most likely to chat all day?",
	"Most likely to cheat on a test?",
	"Most likely to cheat on their spouse?",
	"Most likely to circumnavigate the globe?",
	"Most likely to climb Mount Everest someday?",
	"Most likely to come from a large family?",
	"Most likely to come from a split family?",
	"Most likely to contract an STD?",
	"Most likely to cook something for dinner?",
	"Most likely to crash an ex’s wedding?",
	"Most likely to crash their car?",
	"Most likely to crash their ex’s wedding?",
	"Most likely to create candy land?",
	"Most likely to cry because of a sad movie?",
	"Most likely to cry during a movie?",
	"Most likely to cry during romantic movies?",
	"Most likely to cry in a public place?",
	"Most likely to cry in public?",
	"Most likely to dance in a public place?",
	"Most likely to develop a new mobile app?",
	"Most likely to die alone?",
	"Most likely to die of an undiscovered disease?",
	"Most likely to die of something stupid?",
	"Most likely to die the weirdest death?",
	"Most likely to do a disgusting thing within next 24 hours?",
	"Most likely to do drugs?",
	"Most likely to do something stupid and be ashamed?",
	"Most likely to do something weird to pay for college?",
	"Most likely to do the bungee jump?",
	"Most likely to do the plastic surgery?",
	"Most likely to do weird things in public?",
	"Most likely to dress nicely?",
	"Most likely to drink more beer?",
	"Most likely to drive a 16 wheeler?",
	"Most likely to drive terribly?",
	"Most likely to Drop a phone in the toilet?",
	"Most likely to eat a tub of ice-cream alone?",
	"Most likely to eat the most number of burgers within 10 minutes?",
	"Most likely to eat weird things?",
	"Most likely to eat with mouth open?",
	"Most likely to embarrass themselves in front of their secret crush / known crush?",
	"Most likely to end up in prison?",
	"Most likely to experience hangover?",
	"Most likely to fail a simple test?",
	"Most likely to fake it until they make it?",
	"Most likely to fall asleep in class?",
	"Most likely to fall down a tree?",
	"Most likely to fall in a mall?",
	"Most likely to fall in love?",
	"Most likely to fall into a trap of a scammer?",
	"Most likely to fall over?",
	"Most likely to fall while walking?",
	"Most likely to fart in a full elevator?",
	"Most likely to fight in public?",
	"Most likely to fight with a gangster?",
	"Most likely to flirt with a stranger?",
	"Most likely to flirt with a widow/widower?",
	"Most likely to fly an airplane?",
	"Most likely to forget his wife’s birthday?",
	"Most likely to forget important birthdays?",
	"Most likely to forget responsibilities?",
	"Most likely to forget their wedding anniversary?",
	"Most likely to forget to brush their teeth?",
	"Most likely to get a drunk tattoo?",
	"Most likely to get a job in another country?",
	"Most likely to get a tattoo?",
	"Most likely to get arrested for walking around naked?",
	"Most likely to get arrested?",
	"Most likely to get caught in an uncompromising position?",
	"Most likely to get chased by a dog?",
	"Most likely to get cheated on?",
	"Most likely to get divorced multiple times?",
	"Most likely to get dressed quickly?",
	"Most likely to get drunk at a funeral?",
	"Most likely to get fired from their job?",
	"Most likely to get in a fight?",
	"Most likely to get into an Ivy League school?",
	"Most likely to get kicked out of a theater for talking during a movie?",
	"Most likely to get married first?",
	"Most likely to get offended by a joke?",
	"Most likely to get pissed on?",
	"Most likely to get robbed?",
	"Most likely to get scared of spiders?",
	"Most likely to get shouted at by their parents?",
	"Most likely to get their car keyed?",
	"Most likely to give all their money to a charity?",
	"Most likely to go a week without a shower?",
	"Most likely to go bankrupt after winning the lottery?",
	"Most likely to go bungee jumping?",
	"Most likely to go fishing?",
	"Most likely to go on a blind date?",
	"Most likely to go on a hunger strike?",
	"Most likely to go to jail?",
	"Most likely to go to the moon?",
	"Most likely to go to the museum very often?",
	"Most likely to hate Valentine’s Day?",
	"Most likely to have a big family?",
	"Most likely to have a crush on a teacher?",
	"Most likely to have a lot of brothers and sisters?",
	"Most likely to have a lot of siblings?",
	"Most likely to have a nightmare within the next week?",
	"Most likely to have a one night stand?",
	"Most likely to have a part-time job?",
	"Most likely to have a secret identity?",
	"Most likely to have a secret lover?",
	"Most likely to have a secret treasure map?",
	"Most likely to have a terrible tattoo?",
	"Most likely to have a weird themed wedding?",
	"Most likely to have always been the heartbreaker?",
	"Most likely to have an affair with a married person?",
	"Most likely to have been the first to kiss a guy/a girl?",
	"Most likely to have children first?",
	"Most likely to have kids in the next five years?",
	"Most likely to have never been in love?",
	"Most likely to have sex more often?",
	"Most likely to have the best senior prank?",
	"Most likely to have the biggest dreams?",
	"Most likely to have the coolest secret talent?",
	"Most likely to have the highest grades?",
	"Most likely to have the largest phone bill for next month?",
	"Most likely to have the longest relationship?",
	"Most likely to have the most amount of money in their bank account within the next 5 years?",
	"Most likely to have the most cliché tattoo?",
	"Most likely to have the most embarrassing tattoo?",
	"Most likely to have the most hair colors in their lifetime?",
	"Most likely to have the most number of children?",
	"Most likely to have the most number of Facebook friends?",
	"Most likely to have the most piercings?",
	"Most likely to have the most side hustles?",
	"Most likely to have the most suspicious appearance?",
	"Most likely to have the most tattoos?",
	"Most likely to have the most terrible cooking skills?",
	"Most likely to have the poorest IQ level?",
	"Most likely to have the strangest tattoo?",
	"Most likely to have their heart broken?",
	"Most likely to have their nudes leaked?",
	"Most likely to have triplets?",
	"Most likely to have weird phobias?",
	"Most likely to hold a grudge?",
	"Most likely to hold their breath for a long period?",
	"Most likely to hold their breath the longest as it possible?",
	"Most likely to invent a new element?",
	"Most likely to invent something extraordinary for the betterment of entire mankind?",
	"Most likely to invent something useful?",
	"Most likely to join the army?",
	"Most likely to join the military?",
	"Most likely to laugh at a wrong moment?",
	"Most likely to laugh at an inappropriate time/place?",
	"Most likely to lie during the most likely to tag?",
	"Most likely to lie to get out of trouble?",
	"Most likely to listen to classical music?",
	"Most likely to live in a big city?",
	"Most likely to live in a zoo?",
	"Most likely to live internationally?",
	"Most likely to live to a hundred years?",
	"Most likely to live with a native tribe?",
	"Most likely to lock themselves out of the house?",
	"Most likely to look mature within next 5 years?",
	"Most likely to lose a verbal argument?",
	"Most likely to lose his house keys?",
	"Most likely to lose his/her phone within the next 6 months?",
	"Most likely to lose their temper?",
	"Most likely to lose weight within the year?",
	"Most likely to make a million dollars?",
	"Most likely to make a phone call to 911?",
	"Most likely to make an inappropriate joke?",
	"Most likely to make some change?",
	"Most likely to make the country proud?",
	"Most likely to make the largest donation to charity?",
	"Most likely to marry a celebrity?",
	"Most likely to marry for money?",
	"Most likely to marry someone from a different country?",
	"Most likely to marry someone their friends and family hate?",
	"Most likely to marry their high school sweetheart?",
	"Most likely to memorize a TV show’s theme song?",
	"Most likely to miss an important event because they slept off?",
	"Most likely to move to a different country?",
	"Most likely to move to a new country?",
	"Most likely to murder a well-known celebrity?",
	"Most likely to never settle down?",
	"Most likely to not wear makeup?",
	"Most likely to order a pizza within next 24 hours?",
	"Most likely to own a cruise ship?",
	"Most likely to own a gun?",
	"Most likely to own a small business?",
	"Most likely to own the most pets?",
	"Most likely to paint their nails most often?",
	"Most likely to pass out on a bar stool?",
	"Most likely to pee their pants?",
	"Most likely to perform a sex change?",
	"Most likely to play the role of a superhero?",
	"Most likely to pull a Kanye on an award stage?",
	"Most likely to pull a prank on the Pope?",
	"Most likely to punch a wall?",
	"Most likely to put on weight within the year?",
	"Most likely to queue behind a mannequin?",
	"Most likely to quit their job to travel the world?",
	"Most likely to read a book within the next month?",
	"Most likely to read every book in a school library?",
	"Most likely to really be a superhero?",
	"Most likely to reinvent themselves?",
	"Most likely to rule the world?",
	"Most likely to run away and disappear without a trace?",
	"Most likely to run away to join the circus?",
	"Most likely to run faster?",
	"Most likely to run naked in public?",
	"Most likely to sell drugs to a uniformed officer?",
	"Most likely to set a Guinness World record for sleeping?",
	"Most likely to set themselves on fire as a protest?",
	"Most likely to shave their head for some reason?",
	"Most likely to skip class?",
	"Most likely to sleep their way to the top?",
	"Most likely to sleep through the day?",
	"Most likely to smoke?",
	"Most likely to snitch or ruin a plan?",
	"Most likely to spend all their money on clothing?",
	"Most likely to spend all their money on food?",
	"Most likely to spend all their money on something stupid?",
	"Most likely to spend Christmas in a bar?",
	"Most likely to spend the entire day playing games?",
	"Most likely to spend the most on makeup?",
	"Most likely to spend the most time on their hair?",
	"Most likely to stalk a crush?",
	"Most likely to stalk their celebrity crush?",
	"Most likely to start a music band at the age of 40?",
	"Most likely to start their own business?",
	"Most likely to start their own religion?",
	"Most likely to stay at home on Friday night?",
	"Most likely to steal candy from a baby?",
	"Most likely to survive a zombie apocalypse?",
	"Most likely to take care of the others when they are sick?",
	"Most likely to talk their way out of a speeding ticket?",
	"Most likely to talk to animals?",
	"Most likely to text in class?",
	"Most likely to travel the world?",
	"Most likely to travel to the moon?",
	"Most likely to trip on air?",
	"Most likely to visit the most countries?",
	"Most likely to volunteer for a humanitarian cause?",
	"Most likely to watch a horror movie alone at night?",
	"Most likely to watch more TV?",
	"Most likely to watch romantic movies?",
	"Most likely to wear the most makeup?",
	"Most likely to wear unwashed underwear?",
	"Most likely to win a game of chess?",
	"Most likely to win a game show?",
	"Most likely to win a Nobel Peace Prize?",
	"Most likely to win a TV game show?",
	"Most likely to win America’s next top model?",
	"Most likely to win an Olympic medal?",
	"Most likely to win an Oscar award?",
	"Most likely to win dancing with the stars?",
	"Most likely to win the lottery?",
	"Most likely to work for NASA?",
	"Most likely to work for the government someday?",
	"Most likely to worry about small things?",
	"Most likely to write a bestselling book?"
];

//=========================================================================

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

var handlers = {
	'LaunchRequest': function () {
		this.emit('GetNewGameIntent');
	},
	'NextQuestion': function () {
		var gameArr = data;
		var gameIndex = Math.floor(Math.random() * gameArr.length);
		var nextQuestion = gameArr[gameIndex];
		var speechOutput = nextQuestion;
		this.emit(':tellWithCard', speechOutput)
	},
	'GetNewGameIntent': function () {
		var gameArr = data;
		var gameIndex = Math.floor(Math.random() * gameArr.length);
		var randomGame = gameArr[gameIndex];
		var speechOutput = GET_GAME_MESSAGE + randomGame;
		this.emit(':tellWithCard', speechOutput, SKILL_NAME, randomGame)
	},
	'AMAZON.HelpIntent': function () {
		var speechOutput = HELP_MESSAGE;
		var reprompt = HELP_REPROMPT;
		this.emit(':ask', speechOutput, reprompt);
	},
	'AMAZON.CancelIntent': function () {
		this.emit(':tell', STOP_MESSAGE);
	},
	'AMAZON.NextIntent': function () {
		this.emit(':tell', )
	}
	'AMAZON.StopIntent': function () {
		this.emit(':tell', STOP_MESSAGE);
	}
}